# Generated by Django 4.2.23 on 2025-06-11 20:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('steps', models.IntegerField(default=10)),
                ('parent_array', models.JSONField(default=list)),
                ('current_turn', models.IntegerField(default=0)),
                ('round', models.IntegerField(default=1)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=0)),
                ('available_numbers', models.JSONField(default=list)),
                ('operands', models.JSONField(default=dict)),
                ('parent_used', models.IntegerField(default=0)),
                ('player_index', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='game.player'),
        ),
    ]
