# Generated by Django 4.2.23 on 2025-06-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_moved',
            field=models.BooleanField(default=False),
        ),
    ]
